# Generated by Django 4.0.3 on 2022-03-20 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('number', models.CharField(max_length=10)),
                ('birth_date', models.DateField()),
                ('address', models.TextField()),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
