# Generated by Django 4.0.3 on 2022-03-20 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_orders'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='hotel_Main_Img',
            field=models.ImageField(default=1, upload_to='images/'),
        ),
    ]
