# Generated by Django 4.0.3 on 2022-03-19 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curd', '0002_alter_employee_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_number', models.TextField()),
            ],
            options={
                'db_table': 'Employee1',
            },
        ),
    ]
