# Generated by Django 4.0.3 on 2022-03-19 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curd', '0004_dreamreal'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee5',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_name', models.CharField(max_length=50)),
                ('emp_email', models.CharField(max_length=50)),
                ('emp_number', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'Employee5',
            },
        ),
        migrations.DeleteModel(
            name='Dreamreal',
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
        migrations.DeleteModel(
            name='Employee1',
        ),
    ]
